baseURL: 'https://jwcaterine.com'
title: ''
theme: "PaperMod"
        
    
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "https://yt3.googleusercontent.com/ZDSd8F6GDLoxfc1_rSGLy5QGiGFaKqb5Ga823oJO5w6cboQksKWe7w10f1-z_AyIPbpWsmTawUM=s176-c-k-c0x00ffffff-no-rj"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags
    homeInfoParams:
        Title: "Howdy, I'm JW Caterine."
        Content: >
            I'm an independent journalist and writer living in Hampton Roads, VA.

    socialIcons: 
        - name: Twitter
          url: "https://twitter.com/jwcat757"
        - name: Instagram
          url: "https://www.instagram.com/jwcat757"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/joseph-caterine-578a73268"
        - name: GitHub
          url: "https://github.com/gam32bit"
        - name: Youtube
          url: "https://www.youtube.com/@JWCat757"

menu:
      main:
         - name: Home
           url: /
           weight: 4
         - name: Archive
           url: archives/
           weight: 5
         - name: Tags
           url: tags/
           weight: 10

